# The Rakefile defines tasks to be run from the command line (view all tasks with `rake -T`)
require_relative './config/environment'
# Require the rake folder in the sinatra activerecord gem to get tasks
require 'sinatra/activerecord/rake'

desc "Start our app console"
task :console do
  Pry.start
end

desc "Say something hipster"
task :hipster do
  puts Faker::Hipster.sentence
end
